name: Build app

on:
  push:
    branches: ["**"]
    tags: ["v*.*.*"]
  pull_request:

jobs:
  build-app:
    uses: les-chauffagistes/deploy/.github/workflows/build.yml@develop
    with:
      service-name: auth-service-front
    secrets: inherit